// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: block.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
insert into block (page_id, parent_block_id, type, content, "order") 
	values ($1, $2, $3, $4, $5) 
	returning id, page_id, parent_block_id, type, content, "order"
`

type CreateBlockParams struct {
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
}

type CreateBlockRow struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.PageID,
		arg.ParentBlockID,
		arg.Type,
		arg.Content,
		arg.Order,
	)
	var i CreateBlockRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ParentBlockID,
		&i.Type,
		&i.Content,
		&i.Order,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
update block 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlock, id)
	return err
}

const getBlocksByPage = `-- name: GetBlocksByPage :many
select id, page_id, parent_block_id, type, content, "order" 
	from block 
	where page_id = $1 
		and deleted_at is null 
	order by "order"
`

type GetBlocksByPageRow struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
}

func (q *Queries) GetBlocksByPage(ctx context.Context, pageID pgtype.UUID) ([]GetBlocksByPageRow, error) {
	rows, err := q.db.Query(ctx, getBlocksByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlocksByPageRow
	for rows.Next() {
		var i GetBlocksByPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ParentBlockID,
			&i.Type,
			&i.Content,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlocksByParent = `-- name: GetBlocksByParent :many
SELECT id, page_id, parent_block_id, type, content, "order"
    FROM block
    WHERE parent_block_id = $1
        AND deleted_at IS NULL
    ORDER BY "order"
`

type GetBlocksByParentRow struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
}

func (q *Queries) GetBlocksByParent(ctx context.Context, parentBlockID pgtype.UUID) ([]GetBlocksByParentRow, error) {
	rows, err := q.db.Query(ctx, getBlocksByParent, parentBlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlocksByParentRow
	for rows.Next() {
		var i GetBlocksByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ParentBlockID,
			&i.Type,
			&i.Content,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootBlocksByPage = `-- name: GetRootBlocksByPage :many
SELECT id, page_id, parent_block_id, type, content, "order"
    FROM block
    WHERE page_id = $1
        AND parent_block_id IS NULL
        AND deleted_at IS NULL
    ORDER BY "order"
`

type GetRootBlocksByPageRow struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
}

func (q *Queries) GetRootBlocksByPage(ctx context.Context, pageID pgtype.UUID) ([]GetRootBlocksByPageRow, error) {
	rows, err := q.db.Query(ctx, getRootBlocksByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRootBlocksByPageRow
	for rows.Next() {
		var i GetRootBlocksByPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ParentBlockID,
			&i.Type,
			&i.Content,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBlocks = `-- name: ReorderBlocks :exec
update block
	set "order" = $1, updated_at = now()
	where id = $2
`

type ReorderBlocksParams struct {
	NewOrder int32
	ID       pgtype.UUID
}

func (q *Queries) ReorderBlocks(ctx context.Context, arg ReorderBlocksParams) error {
	_, err := q.db.Exec(ctx, reorderBlocks, arg.NewOrder, arg.ID)
	return err
}

const restoreBlock = `-- name: RestoreBlock :exec
update block 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestoreBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreBlock, id)
	return err
}

const updateBlock = `-- name: UpdateBlock :one
update block 
	set type = $1, content = $2, updated_at = now() 
	where id = $3 
	returning id, type, content, updated_at
`

type UpdateBlockParams struct {
	Type    string
	Content []byte
	ID      pgtype.UUID
}

type UpdateBlockRow struct {
	ID        pgtype.UUID
	Type      string
	Content   []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (UpdateBlockRow, error) {
	row := q.db.QueryRow(ctx, updateBlock, arg.Type, arg.Content, arg.ID)
	var i UpdateBlockRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
