// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdge = `-- name: CreateEdge :exec
insert into edge (from_id, from_type, to_id, to_type, link_type) values ($1, $2, $3, $4, $5)
`

type CreateEdgeParams struct {
	FromID   pgtype.UUID
	FromType string
	ToID     pgtype.UUID
	ToType   string
	LinkType string
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.Exec(ctx, createEdge,
		arg.FromID,
		arg.FromType,
		arg.ToID,
		arg.ToType,
		arg.LinkType,
	)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
delete from edge where from_id = $1 and to_id = $2 and link_type = $3
`

type DeleteEdgeParams struct {
	FromID   pgtype.UUID
	ToID     pgtype.UUID
	LinkType string
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteEdge, arg.FromID, arg.ToID, arg.LinkType)
	return err
}

const getBacklinks = `-- name: GetBacklinks :many
select from_id, from_type, link_type from edge where to_id = $1
`

type GetBacklinksRow struct {
	FromID   pgtype.UUID
	FromType string
	LinkType string
}

func (q *Queries) GetBacklinks(ctx context.Context, toID pgtype.UUID) ([]GetBacklinksRow, error) {
	rows, err := q.db.Query(ctx, getBacklinks, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBacklinksRow
	for rows.Next() {
		var i GetBacklinksRow
		if err := rows.Scan(&i.FromID, &i.FromType, &i.LinkType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdges = `-- name: GetEdges :many
select from_id, from_type, to_id, to_type, link_type from edge
`

type GetEdgesRow struct {
	FromID   pgtype.UUID
	FromType string
	ToID     pgtype.UUID
	ToType   string
	LinkType string
}

func (q *Queries) GetEdges(ctx context.Context) ([]GetEdgesRow, error) {
	rows, err := q.db.Query(ctx, getEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEdgesRow
	for rows.Next() {
		var i GetEdgesRow
		if err := rows.Scan(
			&i.FromID,
			&i.FromType,
			&i.ToID,
			&i.ToType,
			&i.LinkType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
