// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdge = `-- name: CreateEdge :exec
insert into edge (from_id, from_type, to_id, to_type, link_type) values ($1, $2, $3, $4, $5)
`

type CreateEdgeParams struct {
	FromID   pgtype.UUID
	FromType string
	ToID     pgtype.UUID
	ToType   string
	LinkType string
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.Exec(ctx, createEdge,
		arg.FromID,
		arg.FromType,
		arg.ToID,
		arg.ToType,
		arg.LinkType,
	)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
delete from edge where from_id = $1 and to_id = $2 and link_type = $3
`

type DeleteEdgeParams struct {
	FromID   pgtype.UUID
	ToID     pgtype.UUID
	LinkType string
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteEdge, arg.FromID, arg.ToID, arg.LinkType)
	return err
}

const deleteEdgesFromPage = `-- name: DeleteEdgesFromPage :exec
DELETE FROM edge WHERE from_id = $1 AND from_type = 'page' AND link_type = 'wiki-link'
`

func (q *Queries) DeleteEdgesFromPage(ctx context.Context, fromID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdgesFromPage, fromID)
	return err
}

const getBacklinkPages = `-- name: GetBacklinkPages :many
select p.id, p.title
	from edge e
	join page p on p.id = e.from_id and p.deleted_at is null
	where e.to_id = $1
		and e.from_type = 'page'
		and e.to_type = 'page'
		and e.link_type = 'wiki-link'
	order by p.title asc
`

type GetBacklinkPagesRow struct {
	ID    pgtype.UUID
	Title string
}

func (q *Queries) GetBacklinkPages(ctx context.Context, toID pgtype.UUID) ([]GetBacklinkPagesRow, error) {
	rows, err := q.db.Query(ctx, getBacklinkPages, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBacklinkPagesRow
	for rows.Next() {
		var i GetBacklinkPagesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBacklinks = `-- name: GetBacklinks :many
select from_id, from_type, link_type from edge where to_id = $1
`

type GetBacklinksRow struct {
	FromID   pgtype.UUID
	FromType string
	LinkType string
}

func (q *Queries) GetBacklinks(ctx context.Context, toID pgtype.UUID) ([]GetBacklinksRow, error) {
	rows, err := q.db.Query(ctx, getBacklinks, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBacklinksRow
	for rows.Next() {
		var i GetBacklinksRow
		if err := rows.Scan(&i.FromID, &i.FromType, &i.LinkType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdges = `-- name: GetEdges :many
select from_id, from_type, to_id, to_type, link_type from edge
`

type GetEdgesRow struct {
	FromID   pgtype.UUID
	FromType string
	ToID     pgtype.UUID
	ToType   string
	LinkType string
}

func (q *Queries) GetEdges(ctx context.Context) ([]GetEdgesRow, error) {
	rows, err := q.db.Query(ctx, getEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEdgesRow
	for rows.Next() {
		var i GetEdgesRow
		if err := rows.Scan(
			&i.FromID,
			&i.FromType,
			&i.ToID,
			&i.ToType,
			&i.LinkType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageIdByTitle = `-- name: GetPageIdByTitle :one
SELECT id FROM page WHERE title = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageIdByTitle(ctx context.Context, title string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPageIdByTitle, title)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
