// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	ParentBlockID pgtype.UUID
	Type          string
	Content       []byte
	Order         int32
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Edge struct {
	FromID    pgtype.UUID
	FromType  string
	ToID      pgtype.UUID
	ToType    string
	LinkType  string
	CreatedAt pgtype.Timestamptz
}

type Page struct {
	ID        pgtype.UUID
	Title     string
	Date      pgtype.Date
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Pocket struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Taggable struct {
	TagID      pgtype.UUID
	TargetID   pgtype.UUID
	TargetType string
}

type Transaction struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
