// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
insert into page (title, date) 
	values ($1, $2) 
	returning id, title, date
`

type CreatePageParams struct {
	Title string
	Date  pgtype.Date
}

type CreatePageRow struct {
	ID    pgtype.UUID
	Title string
	Date  pgtype.Date
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage, arg.Title, arg.Date)
	var i CreatePageRow
	err := row.Scan(&i.ID, &i.Title, &i.Date)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
update page 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getAllPages = `-- name: GetAllPages :many
select id, title, date 
	from page 
	where deleted_at is null
`

type GetAllPagesRow struct {
	ID    pgtype.UUID
	Title string
	Date  pgtype.Date
}

func (q *Queries) GetAllPages(ctx context.Context) ([]GetAllPagesRow, error) {
	rows, err := q.db.Query(ctx, getAllPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPagesRow
	for rows.Next() {
		var i GetAllPagesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageByID = `-- name: GetPageByID :one
select id, title, date 
	from page 
	where id = $1 
		and deleted_at is null
`

type GetPageByIDRow struct {
	ID    pgtype.UUID
	Title string
	Date  pgtype.Date
}

func (q *Queries) GetPageByID(ctx context.Context, id pgtype.UUID) (GetPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i GetPageByIDRow
	err := row.Scan(&i.ID, &i.Title, &i.Date)
	return i, err
}

const restorePage = `-- name: RestorePage :exec
update page 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestorePage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePage, id)
	return err
}

const updatePage = `-- name: UpdatePage :one
update page 
	set title = $1, date = $2, updated_at = now() 
	where id = $3 
	returning id, title, date, updated_at
`

type UpdatePageParams struct {
	Title string
	Date  pgtype.Date
	ID    pgtype.UUID
}

type UpdatePageRow struct {
	ID        pgtype.UUID
	Title     string
	Date      pgtype.Date
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (UpdatePageRow, error) {
	row := q.db.QueryRow(ctx, updatePage, arg.Title, arg.Date, arg.ID)
	var i UpdatePageRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Date,
		&i.UpdatedAt,
	)
	return i, err
}
