// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pocket.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPocket = `-- name: CreatePocket :one
insert into pocket (name, type) 
	values ($1, $2) 
	returning id, name, type, created_at, updated_at
`

type CreatePocketParams struct {
	Name string
	Type string
}

type CreatePocketRow struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePocket(ctx context.Context, arg CreatePocketParams) (CreatePocketRow, error) {
	row := q.db.QueryRow(ctx, createPocket, arg.Name, arg.Type)
	var i CreatePocketRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePocket = `-- name: DeletePocket :exec
update pocket 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeletePocket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePocket, id)
	return err
}

const getAllPockets = `-- name: GetAllPockets :many
select id, name, type, deleted_at, updated_at
	from pocket 
	where deleted_at is null
`

type GetAllPocketsRow struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetAllPockets(ctx context.Context) ([]GetAllPocketsRow, error) {
	rows, err := q.db.Query(ctx, getAllPockets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPocketsRow
	for rows.Next() {
		var i GetAllPocketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPocketBalances = `-- name: GetPocketBalances :many
select
	p.id,
	p.name,
	p.type,
	coalesce(sum(
		case
			when t.type = 'expense' and t.from_pocket_id = p.id then -t.amount
			when t.type = 'income' and t.to_pocket_id = p.id then t.amount
			when t.type = 'transfer' and t.to_pocket_id = p.id then t.amount
			when t.type = 'transfer' and t.from_pocket_id = p.id then -t.amount
			else 0
		end
	), 0)::numeric as balance
from pocket p
left join transaction t
	on (t.from_pocket_id = p.id or t.to_pocket_id = p.id)
	and t.deleted_at is null
where p.deleted_at is null
group by p.id
order by p.updated_at desc
`

type GetPocketBalancesRow struct {
	ID      pgtype.UUID
	Name    string
	Type    string
	Balance pgtype.Numeric
}

func (q *Queries) GetPocketBalances(ctx context.Context) ([]GetPocketBalancesRow, error) {
	rows, err := q.db.Query(ctx, getPocketBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPocketBalancesRow
	for rows.Next() {
		var i GetPocketBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePocket = `-- name: RestorePocket :exec
update pocket 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestorePocket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePocket, id)
	return err
}

const updatePocket = `-- name: UpdatePocket :one
update pocket 
	set name = $1, type = $2, updated_at = now() 
	where id = $3 
	returning id, name, type, updated_at
`

type UpdatePocketParams struct {
	Name string
	Type string
	ID   pgtype.UUID
}

type UpdatePocketRow struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePocket(ctx context.Context, arg UpdatePocketParams) (UpdatePocketRow, error) {
	row := q.db.QueryRow(ctx, updatePocket, arg.Name, arg.Type, arg.ID)
	var i UpdatePocketRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.UpdatedAt,
	)
	return i, err
}
