// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
insert into tag (name, color) 
	values ($1, $2) 
	on conflict (name) do update 
		set deleted_at = null, updated_at = now() 
	returning id, name, color
`

type CreateTagParams struct {
	Name  string
	Color string
}

type CreateTagRow struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color)
	var i CreateTagRow
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
update tag 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getAllTags = `-- name: GetAllTags :many
select id, name, color 
	from tag 
	where deleted_at is null
`

type GetAllTagsRow struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) GetAllTags(ctx context.Context) ([]GetAllTagsRow, error) {
	rows, err := q.db.Query(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTagsRow
	for rows.Next() {
		var i GetAllTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTag = `-- name: RestoreTag :exec
update tag 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestoreTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreTag, id)
	return err
}

const updateTag = `-- name: UpdateTag :one
update tag 
	set name = $1, color = $2, updated_at = now() 
	where id = $3 
	returning id, name, color, updated_at
`

type UpdateTagParams struct {
	Name  string
	Color string
	ID    pgtype.UUID
}

type UpdateTagRow struct {
	ID        pgtype.UUID
	Name      string
	Color     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.UpdatedAt,
	)
	return i, err
}
