// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taggable.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTag = `-- name: AttachTag :exec
insert into taggable (tag_id, target_id, target_type) 
	values ($1, $2, $3)
`

type AttachTagParams struct {
	TagID      pgtype.UUID
	TargetID   pgtype.UUID
	TargetType string
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.TagID, arg.TargetID, arg.TargetType)
	return err
}

const detachTag = `-- name: DetachTag :exec
delete from taggable 
	where tag_id = $1 
		and target_id = $2 
		and target_type = $3
`

type DetachTagParams struct {
	TagID      pgtype.UUID
	TargetID   pgtype.UUID
	TargetType string
}

func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) error {
	_, err := q.db.Exec(ctx, detachTag, arg.TagID, arg.TargetID, arg.TargetType)
	return err
}

const getTagsByTarget = `-- name: GetTagsByTarget :many
select t.id, t.name, t.color 
	from tag t
	inner join taggable tg 
		on t.id = tg.tag_id
	where tg.target_id = $1 
		and tg.target_type = $2
`

type GetTagsByTargetParams struct {
	TargetID   pgtype.UUID
	TargetType string
}

type GetTagsByTargetRow struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) GetTagsByTarget(ctx context.Context, arg GetTagsByTargetParams) ([]GetTagsByTargetRow, error) {
	rows, err := q.db.Query(ctx, getTagsByTarget, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByTargetRow
	for rows.Next() {
		var i GetTagsByTargetRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
