// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taggable.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTag = `-- name: AttachTag :exec
insert into taggable (tag_id, target_id, target_type) 
	values ($1, $2, $3)
	on conflict (tag_id, target_id, target_type) do nothing
`

type AttachTagParams struct {
	TagID      pgtype.UUID
	TargetID   pgtype.UUID
	TargetType string
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.TagID, arg.TargetID, arg.TargetType)
	return err
}

const detachTag = `-- name: DetachTag :exec
delete from taggable 
	where tag_id = $1 
		and target_id = $2 
		and target_type = $3
`

type DetachTagParams struct {
	TagID      pgtype.UUID
	TargetID   pgtype.UUID
	TargetType string
}

func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) error {
	_, err := q.db.Exec(ctx, detachTag, arg.TagID, arg.TargetID, arg.TargetType)
	return err
}

const getPagesByTag = `-- name: GetPagesByTag :many
select p.id, p.title
	from page p
	inner join taggable tg on tg.target_id = p.id
	inner join tag t on t.id = tg.tag_id
	where tg.tag_id = $1
		and tg.target_type = 'page'
		and p.deleted_at is null
		and t.deleted_at is null
	order by p.updated_at desc
	limit 50
`

type GetPagesByTagRow struct {
	ID    pgtype.UUID
	Title string
}

func (q *Queries) GetPagesByTag(ctx context.Context, tagID pgtype.UUID) ([]GetPagesByTagRow, error) {
	rows, err := q.db.Query(ctx, getPagesByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPagesByTagRow
	for rows.Next() {
		var i GetPagesByTagRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByTarget = `-- name: GetTagsByTarget :many
select t.id, t.name, t.color 
	from tag t
	inner join taggable tg 
		on t.id = tg.tag_id
	where tg.target_id = $1 
		and tg.target_type = $2
		and t.deleted_at is null
`

type GetTagsByTargetParams struct {
	TargetID   pgtype.UUID
	TargetType string
}

type GetTagsByTargetRow struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) GetTagsByTarget(ctx context.Context, arg GetTagsByTargetParams) ([]GetTagsByTargetRow, error) {
	rows, err := q.db.Query(ctx, getTagsByTarget, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByTargetRow
	for rows.Next() {
		var i GetTagsByTargetRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
