// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
insert into transaction (title, type, amount, date, from_pocket_id, to_pocket_id) 
	values ($1, $2, $3, $4, $5, $6) 
	returning id, title, type, amount, date, from_pocket_id, to_pocket_id
`

type CreateTransactionParams struct {
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

type CreateTransactionRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.Date,
		arg.FromPocketID,
		arg.ToPocketID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
update transaction 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
select id, title, type, amount, date, from_pocket_id, to_pocket_id 
	from transaction 
	where deleted_at is null
`

type GetAllTransactionsRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) GetAllTransactions(ctx context.Context) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.Date,
			&i.FromPocketID,
			&i.ToPocketID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedTransactions = `-- name: GetDeletedTransactions :many
select id, title, type, amount, date, deleted_at
	from transaction
	where deleted_at is not null
	order by deleted_at desc
	limit 50
`

type GetDeletedTransactionsRow struct {
	ID        pgtype.UUID
	Title     string
	Type      string
	Amount    pgtype.Numeric
	Date      pgtype.Date
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetDeletedTransactions(ctx context.Context) ([]GetDeletedTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getDeletedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeletedTransactionsRow
	for rows.Next() {
		var i GetDeletedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.Date,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
select
	coalesce(sum(case when type = 'income' then amount end), 0)::numeric as income,
	coalesce(sum(case when type = 'expense' then amount end), 0)::numeric as expense,
	coalesce(sum(case when type = 'transfer' then amount end), 0)::numeric as transfer
	from transaction
	where deleted_at is null
		and date >= date_trunc('month', now())
		and date < date_trunc('month', now()) + interval '1 month'
`

type GetMonthlySummaryRow struct {
	Income   pgtype.Numeric
	Expense  pgtype.Numeric
	Transfer pgtype.Numeric
}

func (q *Queries) GetMonthlySummary(ctx context.Context) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary)
	var i GetMonthlySummaryRow
	err := row.Scan(&i.Income, &i.Expense, &i.Transfer)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
select id, title, type, amount, date, from_pocket_id, to_pocket_id 
	from transaction 
	where id = $1 
		and deleted_at is null
`

type GetTransactionByIDRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
	)
	return i, err
}

const getTransactionsByFilter = `-- name: GetTransactionsByFilter :many
select
	t.id,
	t.title,
	t.type,
	t.amount,
	t.date,
	t.from_pocket_id,
	t.to_pocket_id,
	fp.name as from_pocket_name,
	tp.name as to_pocket_name
from transaction t
left join pocket fp on fp.id = t.from_pocket_id
left join pocket tp on tp.id = t.to_pocket_id
where t.deleted_at is null
	and ($1::uuid is null or t.from_pocket_id = $1 or t.to_pocket_id = $1)
	and ($2::date is null or t.date >= $2)
	and ($3::date is null or t.date <= $3)
order by t.date desc, t.created_at desc
limit 50
`

type GetTransactionsByFilterParams struct {
	PocketID pgtype.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type GetTransactionsByFilterRow struct {
	ID             pgtype.UUID
	Title          string
	Type           string
	Amount         pgtype.Numeric
	Date           pgtype.Date
	FromPocketID   pgtype.UUID
	ToPocketID     pgtype.UUID
	FromPocketName pgtype.Text
	ToPocketName   pgtype.Text
}

func (q *Queries) GetTransactionsByFilter(ctx context.Context, arg GetTransactionsByFilterParams) ([]GetTransactionsByFilterRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByFilter, arg.PocketID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByFilterRow
	for rows.Next() {
		var i GetTransactionsByFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.Date,
			&i.FromPocketID,
			&i.ToPocketID,
			&i.FromPocketName,
			&i.ToPocketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsWithPocketNames = `-- name: GetTransactionsWithPocketNames :many
select
	t.id,
	t.title,
	t.type,
	t.amount,
	t.date,
	t.from_pocket_id,
	t.to_pocket_id,
	fp.name as from_pocket_name,
	tp.name as to_pocket_name
from transaction t
left join pocket fp on fp.id = t.from_pocket_id
left join pocket tp on tp.id = t.to_pocket_id
where t.deleted_at is null
order by t.date desc, t.created_at desc
limit 50
`

type GetTransactionsWithPocketNamesRow struct {
	ID             pgtype.UUID
	Title          string
	Type           string
	Amount         pgtype.Numeric
	Date           pgtype.Date
	FromPocketID   pgtype.UUID
	ToPocketID     pgtype.UUID
	FromPocketName pgtype.Text
	ToPocketName   pgtype.Text
}

func (q *Queries) GetTransactionsWithPocketNames(ctx context.Context) ([]GetTransactionsWithPocketNamesRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsWithPocketNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsWithPocketNamesRow
	for rows.Next() {
		var i GetTransactionsWithPocketNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.Date,
			&i.FromPocketID,
			&i.ToPocketID,
			&i.FromPocketName,
			&i.ToPocketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransaction = `-- name: RestoreTransaction :exec
update transaction 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestoreTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreTransaction, id)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
update transaction 
	set title = $1, 
			type = $2, 
			amount = $3, 
			date = $4, 
			from_pocket_id = coalesce($5, from_pocket_id), 
			to_pocket_id = coalesce($6, to_pocket_id), 
			updated_at = now() 
	where id = $7 
	returning id, title, type, amount, date, from_pocket_id, to_pocket_id, updated_at
`

type UpdateTransactionParams struct {
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
	ID           pgtype.UUID
}

type UpdateTransactionRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.Date,
		arg.FromPocketID,
		arg.ToPocketID,
		arg.ID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
		&i.UpdatedAt,
	)
	return i, err
}
