// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
insert into transaction (title, type, amount, date, from_pocket_id, to_pocket_id) 
	values ($1, $2, $3, $4, $5, $6) 
	returning id, title, type, amount, date, from_pocket_id, to_pocket_id
`

type CreateTransactionParams struct {
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

type CreateTransactionRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.Date,
		arg.FromPocketID,
		arg.ToPocketID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
update transaction 
	set deleted_at = now() 
	where id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
select id, title, type, amount, date, from_pocket_id, to_pocket_id 
	from transaction 
	where deleted_at is null
`

type GetAllTransactionsRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) GetAllTransactions(ctx context.Context) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.Date,
			&i.FromPocketID,
			&i.ToPocketID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
select id, title, type, amount, date, from_pocket_id, to_pocket_id 
	from transaction 
	where id = $1 
		and deleted_at is null
`

type GetTransactionByIDRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
}

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
	)
	return i, err
}

const restoreTransaction = `-- name: RestoreTransaction :exec
update transaction 
	set deleted_at = null 
	where id = $1
`

func (q *Queries) RestoreTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreTransaction, id)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
update transaction 
	set title = $1, 
			type = $2, 
			amount = $3, 
			date = $4, 
			from_pocket_id = $5, 
			to_pocket_id = $6, 
			updated_at = now() 
	where id = $7 
	returning id, title, type, amount, date, from_pocket_id, to_pocket_id, updated_at
`

type UpdateTransactionParams struct {
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
	ID           pgtype.UUID
}

type UpdateTransactionRow struct {
	ID           pgtype.UUID
	Title        string
	Type         string
	Amount       pgtype.Numeric
	Date         pgtype.Date
	FromPocketID pgtype.UUID
	ToPocketID   pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.Date,
		arg.FromPocketID,
		arg.ToPocketID,
		arg.ID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.Date,
		&i.FromPocketID,
		&i.ToPocketID,
		&i.UpdatedAt,
	)
	return i, err
}
