// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package modules

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ConfirmCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-show=\"confirmCard\" @keydown.escape.window=\"cancelDelete()\" class=\"fixed inset-0 z-50 flex items-center justify-center\"><div @click=\"cancelDelete()\" class=\"absolute inset-0 bg-black/50\"></div><div class=\"relative w-80 rounded-xl border border-zinc-800 bg-zinc-950 p-5 shadow-2xl\"><p class=\"text-sm text-zinc-200\" x-text=\"confirmCard?.message\"></p><div class=\"mt-5 flex justify-end gap-2\"><button @click=\"cancelDelete()\" class=\"cursor-pointer rounded-lg border border-zinc-700 px-3 py-1.5 text-sm text-zinc-300 hover:border-zinc-500 hover:text-white transition-colors duration-100\">Cancel</button> <button @click=\"doDelete()\" class=\"cursor-pointer rounded-lg border border-red-800 px-3 py-1.5 text-sm text-red-400 hover:border-red-500 hover:text-red-300 transition-colors duration-100\">Delete</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
